### ISSUE TITLE
Browsing a file in the remote repository adds a superfluous path separator after the branch name

### ISSUE THREAD

**Issue by gstokkink** [dinhhuy258/git.nvim#10]
When I try to browse a specific file on the remote repository using `<Leader>go`, a superfluous path separator is placed after the branch name in the URL. The URL still works, but it just looks a bit silly. Very minor bug 😉 

For instance, when I try to browse the file `foo/bar/baz` on branch `quux` using Github, the generated URL is `https://github.com/../blob/quux//foo/bar/baz` instead of `https://github.com/../blob/quux/foo/bar/baz`.

**Comment by dinhhuy258** [comment]
This issue is fixed in the pull request: https://github.com/dinhhuy258/git.nvim/pull/12
