### ISSUE TITLE
Blame not open 

### ISSUE THREAD

**Issue by katinbox** [dinhhuy258/git.nvim#15]
Hi, before update, it working like a charm but now, when i using <Leader>gb, status line show open not panel not like: 
![git](https://user-images.githubusercontent.com/43630437/191683660-61895092-196f-463b-9d29-1edabb1183d1.png)

**Comment by dinhhuy258** [comment]
Sorry, I don't understand your description. Could you please provide some information regarding the issue that you are facing:
- What command causes the bug?
- How to trigger the bug
- Expected result
- Actual result

what does `before update` mean? 

thank you...

**Comment by katinbox** [comment]
Oh, I get full error message: 
![error](https://user-images.githubusercontent.com/43630437/191687825-c512cf98-9e78-4e43-a6eb-fbe26d716b57.png)

**Comment by dinhhuy258** [comment]
Hmm 
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/17776979/191913507-97caa739-0b93-4932-bf15-9c209d67e8e8.png">

I can not reproduce it on my local machine. Let me try to set up fish on my local and try again...

**Comment by dinhhuy258** [comment]
Could you please help me to add the following line of code to `blame.lua` file inside `git.nvim` project to see if the problem is gone? 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/17776979/191914901-84cfbd5b-ed29-45ab-b8a3-85e6c9a43377.png">

**Comment by katinbox** [comment]
Oki, Let's me try

**Comment by dinhhuy258** [comment]
If still does not work, please add the following debug line to trace which line causes the issue.. Thank you so much

<img width="690" alt="image" src="https://user-images.githubusercontent.com/17776979/191917358-15eee1f4-cb9f-439c-867c-14efc27d4fa1.png">

**Comment by katinbox** [comment]
Holy! This custom script i installed make this error, there: https://github.com/G2-Games/welcome.sh
When i remove auto script on fish config file and try again, It working like a charm :v: 
![fixed](https://user-images.githubusercontent.com/43630437/191919005-e056f051-2e7f-446a-85ba-0515c9057a9d.png)
