### ISSUE TITLE
I can't use :GitBlame

### ISSUE THREAD

**Issue by ghost** [dinhhuy258/git.nvim#18]
E5108: Error executing lua Vim:E903: Process failed to start: no such file or directory: "fish"
stack traceback:
        [C]: in function 'jobstart'
        ...m-data\site\pack\packer\start\git.nvim/lua/git/blame.lua:272: in function 'blame'
        [string ":lua"]:1: in main chunk

This is an error i don't know how to fix it. I try to google it but nothing, i need your help @dinhhuy258. Thank you so much.

Fixed!

**Comment by hiimnhan** [comment]
@infa99 I face the same issue. How did you fix it?

**Comment by datdoan** [comment]
I am on windows and had the same issue. I've used someone else .config and they had 
```shell
vim.opt.shell = "fish"
```
If you have the same, just commented/remove it out, your gitblame should works.
