### ISSUE TITLE
Feature Request: Pad top of :GitBlame when using a winbar

### ISSUE THREAD

**Issue by aquillano** [dinhhuy258/git.nvim#19]
## Problem

When setting a winbar, like lspsaga does by default, :GitBlame is off by 1 line.

## Solution

Detect if winbar is set and pad top of :GitBlame buffer to keep blame lines aligned with source code.

**Comment by dinhhuy258** [comment]
Hi aquillano,

Thank you very much for your report.

Could you please provide me with some demonstration configuration + demo (photo) . It can help me to identify the issue quickly.

Thank you

**Comment by iven** [comment]
I've also got this issue, here's screenshot:
![WX20230411-131028](https://user-images.githubusercontent.com/56165/231062132-a4efc937-4eb5-4d1a-8fa0-f8313661c268.png)

**Comment by frantisekstanko** [comment]
My temporary workaround for this is hiding barbecue before opening GitBlame. The whole lazy.nvim config looks like this:

```lua
return {
    "dinhhuy258/git.nvim",
    config = function()
        require("git").setup({
            default_mappings = false,
        })
    end,
    keys = {
        {
            "<leader>gb",
            function()
                require("barbecue.ui").toggle(false)
                vim.cmd("GitBlame")
            end,
            desc = "Git blame",
        },
    },
}
```

However, it would truly be nice to not have to do this. Fugitive has this same bug.

**Comment by dinhhuy258** [comment]
Hi @frantisekstanko  thank you very much for your support... Feel free to open a pr to fix it as i am quite busy these days :(

**Comment by frantisekstanko** [comment]
This feature is now available, so this issue should probably be closed.

To enable winbar, set `winbar = true` in the plugin config.
