### ISSUE TITLE
Last character of blame line wraps

### ISSUE THREAD

**Issue by rawhat** [dinhhuy258/git.nvim#2]
The blame window entries seem to maybe be a little too narrow?  Not sure if there's some config I need to set.  Increasing the buffer width does seem to fix it, but that's probably not the ideal solution.  Attached is a screenshot:

![image](https://user-images.githubusercontent.com/2095509/131223972-41f41d9f-fd80-4cfa-9b47-853cbbb14b2f.png)

Let me know if I can provide any additional info!  Thank you.

**Comment by dinhhuy258** [comment]
Thanks for reporting the bug. Could you please pull the latest commit and try again. I disable the wrap option for win blame

**Comment by rawhat** [comment]
Looks great, thank you!
