### ISSUE TITLE
Git browse builds wrong URL since latest update

### ISSUE THREAD

**Issue by gstokkink** [dinhhuy258/git.nvim#21]
Hi!

First of all, thank you for maintaining this plugin. I use it a lot.

However, since your most recent update (https://github.com/dinhhuy258/git.nvim/pull/20) the Git browse functionality no longer builds the correct URL. It looks like it no longer takes the work directory into account correctly. Say I use Git browse on the file `foo/bar` with work directory `/user/baz/quux` and the git root in `/user/baz`, the resulting Github URL should be `github.com/repo/blob/branch/baz/quux/foo/bar`. Since the latest update, however, the resulting URL will be `github.com/repo/blob/branch/foo/bar` instead.

Thanks for looking into this!

**Comment by dinhhuy258** [comment]
Hi gstokkink, let me have a look this weekend. Thanks for reporting.

**Comment by dinhhuy258** [comment]
I have fixed the issue, this is the pr:
https://github.com/dinhhuy258/git.nvim/pull/22

Feel free to re-open it if the issue still exists on your site.

Thank you.

**Comment by gstokkink** [comment]
@dinhhuy258 that fixed it, thanks! 👍

**Comment by gstokkink** [comment]
@dinhhuy258 

I still run into two small issues unfortunately. First of all, the URL generated is `github.com/repo/blob/branch/baz//quux/foo/bar` rather than `github.com/repo/blob/branch/baz/quux/foo/bar`. One forward slash too many 😉 Furthermore, previously the line number was also appended if I'm not mistaken. So if your cursor was on line 66 of `foo/bar`, the generated URL would be `github.com/repo/blob/branch/baz//quux/foo/bar#L66`. 

I tried to re-open this issue as you instructed but it seems there is no option for that?

Thank you for your hard work on this useful plugin!

**Comment by dinhhuy258** [comment]
Let me reopen this issue and take a look next Thursday. I have been quite busy recently so I may not be able to fix it soon.

**Comment by gstokkink** [comment]
@dinhhuy258 if you want, I can create a PR?

**Comment by dinhhuy258** [comment]
Hi @gstokkink, the merge request looks good to me... I merged it already....  Thank you for your contribution...
