### ISSUE TITLE
Skip default mapping

### ISSUE THREAD

**Issue by mario-amazing** [dinhhuy258/git.nvim#9]
Could you add flag for skip default mappings?

**Comment by dinhhuy258** [comment]
Ya, it's a good idea. I will quickly implement that feature

**Comment by dinhhuy258** [comment]
https://github.com/dinhhuy258/git.nvim/pull/11 this pull request has resolved the problem. Please refer to the README.md for the new configuration `custom_only` flag. Thank you

**Comment by mario-amazing** [comment]
@dinhhuy258 Thanks!
IMHO in README, this configuration flag is not obvious.

**Comment by dinhhuy258** [comment]
Hi @mario-amazing  
Thank you. Do you have any suggestions for me? 
I am not a native English speaker; it would be good if you could help me choose a meaningful configuration flag.

**Comment by mario-amazing** [comment]
I'm not native as well))
So I created PR(above) which looks more appropriate in my opinion. If you have any notes, feel free to tell me in PR

**Comment by dinhhuy258** [comment]
Ya, thank you...
